# Generated by Django 5.2.8 on 2025-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationclause',
            name='measurement_basis',
            field=models.TextField(blank=True),
        ),
    ]
