# Generated by Django 5.2.8 on 2025-11-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_regulationclause_measurement_basis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costitem',
            old_name='description',
            new_name='cost_type',
        ),
        migrations.RemoveField(
            model_name='costitem',
            name='unit',
        ),
    ]
