# Generated by Django 5.2.8 on 2025-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_description_costitem_cost_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='item_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='step_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='regulationclause',
            name='clause_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='costitem',
            index=models.Index(fields=['document', 'item_id'], name='core_costit_documen_bc14ec_idx'),
        ),
        migrations.AddIndex(
            model_name='processstep',
            index=models.Index(fields=['document', 'step_id'], name='core_proces_documen_c3eaea_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationclause',
            index=models.Index(fields=['document', 'clause_ref'], name='core_regula_documen_ff2ebf_idx'),
        ),
    ]
