# Generated by Django 5.2.8 on 2025-11-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_costitem_item_id_alter_processstep_step_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='actor',
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=models.Index(fields=['document', 'text'], name='core_textch_documen_a9e802_idx'),
        ),
    ]
