# Generated by Django 5.2.8 on 2025-11-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_processstep_actor_alter_textchunk_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('SCHEDULE', 'Project Schedule'), ('COSTING', 'Construction Planning & Costing'), ('URA', 'URA GFA Circular'), ('APPROVALS', 'Construction Approvals Flow')], max_length=32),
        ),
    ]
