# Generated by Django 5.2.8 on 2025-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_doc_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='textchunk',
            name='core_textch_documen_a9e802_idx',
        ),
        migrations.AddField(
            model_name='textchunk',
            name='text_hash',
            field=models.CharField(db_index=True, default='', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=models.Index(fields=['document', 'text_hash'], name='core_textch_documen_261a44_idx'),
        ),
    ]
